# Generated by Django 4.1 on 2023-07-31 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('два года', 'два года'), ('год (после 9)', '10 год (после 9)'), ('год (после 9 и 11)', 'год (после 9 и 11)')], max_length=50, null=True, unique=True)),
                ('education_form', models.CharField(choices=[('контракт', 'контракт'), ('бюджет', 'бюджет')], max_length=50)),
                ('for_edu', models.CharField(choices=[('9', '9'), ('11', '11'), ('9 и 11', '9 и 11')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('man', 'мужчина'), ('woman', 'женщина')], default='', max_length=50)),
                ('age', models.DateField(verbose_name='data')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=50, null=True)),
                ('form_education', models.CharField(choices=[('контракт', 'контракт'), ('бюджет', 'бюджет')], max_length=50)),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_db.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='speciality',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_db.teacher'),
        ),
    ]
