# Generated by Django 4.1 on 2023-08-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_db', '0002_plan_subjectplan_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subjectplan',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='SubjectPlan',
        ),
    ]
