# Generated by Django 4.1 on 2023-08-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_db', '0003_remove_subjectplan_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('course', models.IntegerField(null=True)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_db.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('cycle', models.CharField(choices=[('профессионально-техническое', 'профессионально-техническое'), ('общеобразовательное', 'общеобразовательное')], max_length=50, null=True)),
                ('total_hours', models.IntegerField(null=True)),
                ('lpz_hours', models.IntegerField(default='0')),
                ('self_study_hours', models.IntegerField(default='0')),
                ('hours_per_course', models.IntegerField(null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_db.plan')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_db.speciality')),
            ],
        ),
    ]
