# Generated by Django 4.1 on 2023-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_db', '0005_teacher_work_alter_speciality_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectplan',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
