# Generated by Django 4.1 on 2023-08-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_db', '0006_subjectplan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subjectplan',
            name='specialization',
        ),
    ]
