# Generated by Django 4.1 on 2023-08-07 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_db', '0008_subjectplan_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectplan',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_db.subject'),
        ),
    ]
